-- Spring Boot runs schema-@@platform@@.sql automatically during startup. -all is the default for all platforms.

DROP TABLE client IF EXISTS;

CREATE TABLE client  (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);

DROP TABLE client_error IF EXISTS;

CREATE TABLE client_error  (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message VARCHAR(1024)
);